// This is the list of supported chains for Lava SDK Beta Gallery. It can be updated dynamically at anytime.

export const chainList = [
    { chainID: "ALFAJORES", chainName: "celo alfajores testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "APT1", chainName: "aptos mainnet", enabledApiInterfaces: ["rest"] },
    { chainID: "ARB1", chainName: "arbitrum mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "ARBN", chainName: "arbitrum nova testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "AVAX", chainName: "avalanche mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "AXELAR", chainName: "axelar mainnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "AXELART", chainName: "axelar testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "BASE", chainName: "base mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "BASET", chainName: "base goerli testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "BSC", chainName: "bsc mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "BSCT", chainName: "bsc testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "CANTO", chainName: "canto mainnet", enabledApiInterfaces: ["grpc", "jsonrpc", "rest", "tendermintrpc"] },
    { chainID: "CELO", chainName: "celo mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "COS3", chainName: "osmosis mainnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "COS4", chainName: "osmosis testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "COS5", chainName: "cosmos hub mainnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "COS5T", chainName: "cosmos hub testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    // { chainID: "COSHUB", chainName: "cosmos hub mainnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    // { chainID: "COSHUBT", chainName: "cosmos hub testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    // { chainID: "COSMOSSDK", chainName: "cosmos sdk", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    // { chainID: "COSMOSSDK45DEP", chainName: "cosmos sdk deprecated apis", enabledApiInterfaces: ["rest"] },
    // { chainID: "COSMOSSDKFULL", chainName: "full cosmos sdk", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    // { chainID: "COSMOSWASM", chainName: "cosmos wasm", enabledApiInterfaces: ["grpc", "rest"] },
    { chainID: "ETH1", chainName: "ethereum mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "EVMOS", chainName: "evmos mainnet", enabledApiInterfaces: ["grpc", "jsonrpc", "rest", "tendermintrpc"] },
    { chainID: "EVMOST", chainName: "evmos testnet", enabledApiInterfaces: ["grpc", "jsonrpc", "rest", "tendermintrpc"] },
    { chainID: "FTM250", chainName: "fantom mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "FTM4002", chainName: "fantom testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "FVM", chainName: "fvm mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "GTH1", chainName: "ethereum testnet goerli", enabledApiInterfaces: ["jsonrpc"] },
    // { chainID: "IBC", chainName: "ibc", enabledApiInterfaces: ["grpc", "rest"] },
    { chainID: "JUN1", chainName: "juno mainnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "JUNT1", chainName: "juno testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "LAV1", chainName: "lava testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "NEAR", chainName: "near mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "NEART", chainName: "near testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "OPTM", chainName: "optimism mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "OPTMT", chainName: "optimism goerli testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "OSMO", chainName: "osmosis mainnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "OSMOT", chainName: "osmosis testnet", enabledApiInterfaces: ["grpc", "rest", "tendermintrpc"] },
    { chainID: "POLYGON1", chainName: "polygon mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "POLYGON1T", chainName: "polygon testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "SOLANA", chainName: "solana main net", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "SOLANAT", chainName: "solana test net", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "STRK", chainName: "starknet mainnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "STRKT", chainName: "starknet testnet", enabledApiInterfaces: ["jsonrpc"] },
    { chainID: "SUIT", chainName: "sui devnet", enabledApiInterfaces: ["jsonrpc"] }
  ];